### ISSUE TITLE
SSAO creates sharp shadows for structures in holes

### ISSUE THREAD

**Issue by GoogleFrog** [lhog/spring-ssao#2]
![image](https://user-images.githubusercontent.com/1318249/57186967-45fd0f00-6f2b-11e9-84e9-955716605b65.png)

**Comment by GoogleFrog** [comment]
Nevermind, this is mostly due to the sun. SSAO just makes the sun shadows more pronounced in this case.

**Comment by lhog** [comment]
I didn't spend too much time on artistic tuning of SSAO. Frankly I wasn't even sure anyone, besides the original requestor, would be interested. Given you seem to be interested, I updated the code such that configuration time constants are more visible and documented, so they can be adjusted to produce a better look: https://github.com/lhog/spring-ssao/blob/master/LuaUI/Widgets/gfx_ssao.lua#L35-L44
